server:
  port: 8001

spring:
  application:
    name: authentication-server
  profiles:
      active: dev
  redis:  #redis相关配置
    password: 123456
  # 配置 nacos 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

logging:
  level:
    per.lx: DEBUG

