server:
  # 当前服务端口
  port: 8030
spring:
  application:
    name: gateway
# 配置Eureka地址
eureka:
  client:
    # 注册中心的访问地址
    service-url:
      defaultZone: http://localhost:8062/eureka/
# 构建路由地址
# zuul:
    # routes:
    #这里可以自定义
      # demo2:
      # 匹配的路由规则
      #  path: /demo/**
      # 路由的目标服务名
      #  serviceId: eureka-provider

zuul:
  routes:
    # 给服务提供者 provider 设置映射
    eureka-provider: /p/**


