server:
  port: 8050
spring:
  application:
    name: feign
  profiles:
    active: dev
  # 配置 nacos 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

# 是否开启熔断器。
feign:
  hystrix:
    enabled: true